server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_java1234_mall?serverTimezone=Asia/Shanghai
    username: root
    password: 12345



mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id????????id??
  configuration:
    map-underscore-to-camel-case: false # ??????
    auto-mapping-behavior: full # ???????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxe4668df4036a33e8
  secret: 6f0d5038ab48e7dbc0aabfa6dc421938
