package com.xwd.wxsc;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
@MapperScan("com.xwd.wxsc.mapper")
public class Java1234MallV3Application {

    public static void main(String[] args) {
        SpringApplication.run(Java1234MallV3Application.class, args);
    }

}
